version: "3.0"
services:
  web:
    container_name: "app"
    image: app
    ports:
      - "5000:5000"
    volumes:
      - /home/wwwroot/app:/home/app
    restart: always
  nginx:
    container_name: "nginx"
    image: nginx:1.16.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/nginx/www:/usr/share/nginx/html
      - /home/nginx/conf.d:/etc/nginx/conf.d
      - /home/nginx/logs:/var/log/nginx
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/nginx/cert:/etc/nginx/cert
    restart: always
  vsftpd:
    container_name: "vsftpd"
    image: fauria/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - /home/wwwroot/files:/home/vsftpd/admin
    environment:
      FTP_USER: admin
      FTP_PASS: 123456
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      LOCAL_UMASK: 022
      REVERSE_LOOKUP_ENABLE: "NO"
    restart: always
